/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    appAccounts: AppAccount;
    appUsers: AppUser;
    deliveryAddresses: DeliveryAddress;
    deliveryFees: DeliveryFee;
    products: Product;
    orders: Order;
    categories: Category;
    productCollections: ProductCollection;
    colors: Color;
    sizes: Size;
    heros: Hero;
    lookBook: LookBook;
    media: Media;
    layoutMedia: LayoutMedia;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    appAccounts: AppAccountsSelect<false> | AppAccountsSelect<true>;
    appUsers: AppUsersSelect<false> | AppUsersSelect<true>;
    deliveryAddresses: DeliveryAddressesSelect<false> | DeliveryAddressesSelect<true>;
    deliveryFees: DeliveryFeesSelect<false> | DeliveryFeesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    productCollections: ProductCollectionsSelect<false> | ProductCollectionsSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    sizes: SizesSelect<false> | SizesSelect<true>;
    heros: HerosSelect<false> | HerosSelect<true>;
    lookBook: LookBookSelect<false> | LookBookSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    layoutMedia: LayoutMediaSelect<false> | LayoutMediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  last_name?: string | null;
  first_name?: string | null;
  roles: ('user' | 'super-admin')[];
  appUserId?: (string | null) | AppUser;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appUsers".
 */
export interface AppUser {
  id: string;
  email: string;
  last_name?: string | null;
  first_name?: string | null;
  username: string;
  hashedPassword?: string | null;
  hashSalt?: string | null;
  hashIterations?: number | null;
  verificationCode?: string | null;
  verificationHash?: string | null;
  verificationTokenExpire?: number | null;
  verificationKind?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appAccounts".
 */
export interface AppAccount {
  id: string;
  name?: string | null;
  picture?: string | null;
  user: string | AppUser;
  issuerName: string;
  scope?: string | null;
  sub: string;
  passkey?: {
    credentialId: string;
    publicKey:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    counter: number;
    transports:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    deviceType: string;
    backedUp: boolean;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveryAddresses".
 */
export interface DeliveryAddress {
  id: string;
  customerId?: (string | null) | User;
  firstname?: string | null;
  lastname?: string | null;
  address: string;
  appartment?: string | null;
  city: string;
  phone: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveryFees".
 */
export interface DeliveryFee {
  id: string;
  state:
    | 'abia'
    | 'adamawa'
    | 'akwa-ibom'
    | 'anambra'
    | 'bauchi'
    | 'bayelsa'
    | 'benue'
    | 'borno'
    | 'cross-river'
    | 'delta'
    | 'ebonyi'
    | 'edo'
    | 'ekiti'
    | 'enugu'
    | 'fct-abuja'
    | 'gombe'
    | 'imo'
    | 'jigawa'
    | 'kaduna'
    | 'kano'
    | 'katsina'
    | 'kebbi'
    | 'kogi'
    | 'kwara'
    | 'lagos'
    | 'nasarawa'
    | 'niger'
    | 'ogun'
    | 'ondo'
    | 'osun'
    | 'oyo'
    | 'plateau'
    | 'rivers'
    | 'sokoto'
    | 'taraba'
    | 'yobe'
    | 'zamfara';
  deliveryFee?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Price In Naira
   */
  price: number;
  category?: (string | Category)[] | null;
  collection?: (string | ProductCollection)[] | null;
  'available colors'?: (string | Color)[] | null;
  'available sizes'?: (string | Size)[] | null;
  images: {
    image: string | Media;
    id?: string | null;
  }[];
  /**
   * please select one of the images you have picked in the images field for the cover image
   */
  cover: string | Media;
  'in stock': boolean;
  orderCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCollections".
 */
export interface ProductCollection {
  id: string;
  hero?: (string | null) | LayoutMedia;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images uploaded should not be above 10MB
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layoutMedia".
 */
export interface LayoutMedia {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: string;
  label: string;
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes".
 */
export interface Size {
  id: string;
  label: string;
  size: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images uploaded should not be above 5MB
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  paymentReference: string;
  transactionReference?: string | null;
  paymentCompleted?: boolean | null;
  amount: string;
  deliveryFee?: number | null;
  grandTotal: string;
  amountPaid: string;
  paymentDate: string;
  paymentDescription?: string | null;
  customerId?: (string | null) | User;
  userEmail: string;
  addressSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  productsSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  productsOrdered?: (string | Product)[] | null;
  status?: ('pending' | 'paid' | 'delivered' | 'cancelled') | null;
  delivered?: boolean | null;
  dateDelivered?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heros".
 */
export interface Hero {
  id: string;
  slug: string;
  hero: string | LayoutMedia;
  title?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lookBook".
 */
export interface LookBook {
  id: string;
  image: string | LayoutMedia;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'appAccounts';
        value: string | AppAccount;
      } | null)
    | ({
        relationTo: 'appUsers';
        value: string | AppUser;
      } | null)
    | ({
        relationTo: 'deliveryAddresses';
        value: string | DeliveryAddress;
      } | null)
    | ({
        relationTo: 'deliveryFees';
        value: string | DeliveryFee;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'productCollections';
        value: string | ProductCollection;
      } | null)
    | ({
        relationTo: 'colors';
        value: string | Color;
      } | null)
    | ({
        relationTo: 'sizes';
        value: string | Size;
      } | null)
    | ({
        relationTo: 'heros';
        value: string | Hero;
      } | null)
    | ({
        relationTo: 'lookBook';
        value: string | LookBook;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'layoutMedia';
        value: string | LayoutMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  last_name?: T;
  first_name?: T;
  roles?: T;
  appUserId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appAccounts_select".
 */
export interface AppAccountsSelect<T extends boolean = true> {
  name?: T;
  picture?: T;
  user?: T;
  issuerName?: T;
  scope?: T;
  sub?: T;
  passkey?:
    | T
    | {
        credentialId?: T;
        publicKey?: T;
        counter?: T;
        transports?: T;
        deviceType?: T;
        backedUp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appUsers_select".
 */
export interface AppUsersSelect<T extends boolean = true> {
  email?: T;
  last_name?: T;
  first_name?: T;
  username?: T;
  hashedPassword?: T;
  hashSalt?: T;
  hashIterations?: T;
  verificationCode?: T;
  verificationHash?: T;
  verificationTokenExpire?: T;
  verificationKind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveryAddresses_select".
 */
export interface DeliveryAddressesSelect<T extends boolean = true> {
  customerId?: T;
  firstname?: T;
  lastname?: T;
  address?: T;
  appartment?: T;
  city?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveryFees_select".
 */
export interface DeliveryFeesSelect<T extends boolean = true> {
  state?: T;
  deliveryFee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  category?: T;
  collection?: T;
  'available colors'?: T;
  'available sizes'?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  cover?: T;
  'in stock'?: T;
  orderCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  paymentReference?: T;
  transactionReference?: T;
  paymentCompleted?: T;
  amount?: T;
  deliveryFee?: T;
  grandTotal?: T;
  amountPaid?: T;
  paymentDate?: T;
  paymentDescription?: T;
  customerId?: T;
  userEmail?: T;
  addressSnapshot?: T;
  productsSnapshot?: T;
  productsOrdered?: T;
  status?: T;
  delivered?: T;
  dateDelivered?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCollections_select".
 */
export interface ProductCollectionsSelect<T extends boolean = true> {
  hero?: T;
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  label?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes_select".
 */
export interface SizesSelect<T extends boolean = true> {
  label?: T;
  size?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heros_select".
 */
export interface HerosSelect<T extends boolean = true> {
  slug?: T;
  hero?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lookBook_select".
 */
export interface LookBookSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layoutMedia_select".
 */
export interface LayoutMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}